### PR TITLE
Plm

### PR DESCRIPTION
**Pull request by fabiobaselice**
Added the PLM code.

### CODE REVIEW

**Comment by fabiobaselice** [comment]
I'm sorry, I forgot to paste one line of code (definition of ntime)

**Comment by schoffelen** [comment]
Just to be sure: what you mean by 'ntime' is actually the 'trial' dimension, i.e. a chunk of discontinuous data. These chunks could have been obtained in various ways, e.g. as epochs defined in an experimental setting, or as a long segment of data having been chunked in shorter snippets as per ft_redefinetrial. 
In both cases, is it meaningful to have a 'per trial' estimate, or do you want a single value per channel pair?

**Comment by fabiobaselice** [comment]
The present code works assuming the input data as a cell array, composed by one matrix (channels number x sample number) for each trial. However, I can easily modify the code for working with a single trial (just one input matrix). Do you prefer this solution?

**Comment by schoffelen** [comment]
No, that's fine, I just wanted to be sure that this is what you think is a meaningful output. We could consider making the integration over trials an option of the function, where I can imagine that it needs to be computed slightly differently than taking an average...

**Pull request merged**
