### PR TITLE
ft_laggedcoherence and test script

### PR DESCRIPTION
**Pull request by hadrianswall**
I added a first version of ft_laggedcoherence and a test script. In this first version, only the ft_freqanalysis step is performed, but using the configuration settings that are required by ft_laggedcoherence. Thus, a lot of bookkeeping operations ...

### CODE REVIEW

**Comment by schoffelen** [comment]
So, what I now wonder about, is how to fit in your heuristic of precomputing the desired tois for ft_freqanalysis. In the current state of the code, this time axis is highly non uniform. I understand the requiremen of the t_ftimwins not to be overlapping is important, but I wonder whether this is the most efficient way of getting there. My suggestion would be to have a uniformly spaced toi with sufficiently small steps between the timepoints, followed by a 'pruning' operation at the level of the computation of the lagged cross spectrum, where (as a function of frequency) only every N'th Fourier data point is taken, with N being the number of points per window.

**Comment by hadrianswall** [comment]
To make your proposal work (using a uniformly spaced toi), we would have to include all possible time points in the toi (i.e., all separated by one sample). That could be done, but then all my precomputing would still have to be performed on the time axis of the resulting time resolved Fourier output. The price would be an extremely large freqanalysis output followed by drastic pruning. 

I could also offer you Fourier output with regularly spaced time axes, but then a different time axis for every frequency. The different points on this time axis can then be used to determine the lags (because the time windows are non-overlapping).

Maybe we should discuss this over the phone ...

**Comment by schoffelen** [comment]
Well, it sounds as if we might then converge back onto doing a 'per frequency' call to ft_freqanalysis, followed by a call to ft_connectivityanalysis, followed by an aggregation of the results across frequencies?

**Comment by schoffelen** [comment]
By the way, I am at home (kids' teachers have 'studiedag') so I could chat, albeit it suboptimal because attention needs to be subdivided.

**Comment by hadrianswall** [comment]
OK. I will implement the first step of the "per frequency" approach and will let you know when I'm done.

**Pull request merged**
